# Generated by Django 4.0.5 on 2022-07-11 03:22

import cs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='photos/users/default.svg', upload_to=cs.models.User.get_upload_path, verbose_name='Фото'),
        ),
    ]
