# Generated by Django 4.0.5 on 2022-07-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0002_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tours_1_place',
            field=models.ManyToManyField(blank=True, related_name='teams_1_place', to='cs.tournament'),
        ),
        migrations.AddField(
            model_name='team',
            name='tours_2_place',
            field=models.ManyToManyField(blank=True, related_name='teams_2_place', to='cs.tournament'),
        ),
        migrations.AddField(
            model_name='team',
            name='tours_3_place',
            field=models.ManyToManyField(blank=True, related_name='teams_3_place', to='cs.tournament'),
        ),
    ]
