# Generated by Django 4.0.5 on 2022-07-12 08:06

import cs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0003_team_tours_1_place_team_tours_2_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bio',
            field=models.TextField(blank=True, max_length='700', verbose_name='Доп. информация'),
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(default='photos/teams/default_team_logo.png', upload_to=cs.models.Team.get_upload_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Игроки'),
        ),
    ]
